[package]
name = "print-run"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
nu-ansi-term = "0.50"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
